name: Terraform Azure Storage Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.terraform.lock.hcl'
      - '**/*.tfvars'

env:
  TF_VAR_environment: ${{ secrets.AZURE_ENVIRONMENT }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: Dev-Plan
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_environment: ${{ secrets.AZURE_ENVIRONMENT }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_location: ${{ secrets.AZURE_LOCATION }}
      TF_VAR_resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      TF_VAR_storageAccountName: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: terraform/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Clean Terraform lock file
        run: rm -f .terraform.lock.hcl

      - name: Terraform Init
        run: terraform init -upgrade -backend-config="key=${TF_VAR_environment}.tfstate"

      
            
      - name: Debug Terraform folder
        run: |
          echo "Current location and files:"
          pwd
          ls -la
          echo "Inspecting terraform subfolder:"
          ls -la ..

      - name: Confirm lock file presence
        run: |
          echo "Current directory: $(pwd)"
          echo "Expected lock file location: $(pwd)/.terraform.lock.hcl"

          if [ ! -f ".terraform.lock.hcl" ]; then
            echo "Lock file not found at $(pwd)/.terraform.lock.hcl"
            echo "Re-running terraform init to generate lock file..."
            terraform init -backend-config="key=${TF_VAR_environment}.tfstate"
          fi

          if [ ! -f ".terraform.lock.hcl" ]; then
            echo "Still missing after init. Exiting safely."

          exit 1
          else
          echo Lock file found!
          fi
      - name: Remove old plan file (if exists)
        run: |
          if [ -f tfplan-${TF_VAR_environment}.out ]; then
            rm tfplan-${TF_VAR_environment}.out
          fi

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false

      - name: Terraform Plan
        run: terraform plan -out=tfplan-${TF_VAR_environment}.out

      - name: Show Terraform plan (human-readable)
        run: terraform show tfplan-${TF_VAR_environment}.out

      - name: Export Terraform plan to JSON
        run: terraform show -json tfplan-${TF_VAR_environment}.out > tfplan-${TF_VAR_environment}.json

      - name: Check if tfplan JSON exists
        run: |
          if test -f tfplan-${TF_VAR_environment}.json; then
            echo "Plan file exists!"
          else
            echo "Plan file NOT found!"
            exit 1
          fi
      - name: List files before upload
        run: ls -la 

      - name: Confirm lock file exists before upload
        run: |
          echo "Current directory: $(pwd)"
          ls -l .terraform.lock.hcl

      - name: Upload tfplan files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ env.TF_VAR_environment }}
          path: |
            terraform/tfplan-${{ env.TF_VAR_environment }}.out
            terraform/tfplan-${{ env.TF_VAR_environment }}.json
          retention-days: 90

      - name: Upload lock file
        if: ${{ env.TF_VAR_environment }}
        uses: actions/upload-artifact@v4
        with:
         name: terraform-lock-${{ env.TF_VAR_environment }}
         path: terraform/.terraform.lock.hcl


      - name: Inspect uploaded artifact
        uses: actions/download-artifact@v4
        with:
         name: terraform-plan-${{ env.TF_VAR_environment }}
         path: verify-artifact/

      - name: List contents
        run: ls -la verify-artifact/


  terraform-apply:
    needs: terraform-plan
    environment: Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_environment: ${{ secrets.AZURE_ENVIRONMENT }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_location: ${{ secrets.AZURE_LOCATION }}
      TF_VAR_resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      TF_VAR_storageAccountName: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show working directory  # Add this debug step early
        run: pwd

      

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ env.TF_VAR_environment }}
          path: terraform/

      - name: Download lock file artifact
        uses: actions/download-artifact@v4
        with:
         name: terraform-lock-${{ env.TF_VAR_environment }}
         path: verify-artifact/


      - name: List files in directory after Artifact Download  # Helps confirm lock file is there
        run: ls -al
      

      - name: Confirm azurerm provider lock before apply
        run: |
          LOCK_FILE=".terraform.lock.hcl"
          echo "Checking for $LOCK_FILE"

          if [ ! -f "$LOCK_FILE" ]; then
            echo "Lock file not found!"

            exit 1
          fi

          if grep -q "registry.terraform.io/hashicorp/azurerm" .terraform.lock.hcl; then
            echo "azurerm provider lock confirmed:"
            grep "registry.terraform.io/hashicorp/azurerm" .terraform.lock.hcl
          else
            echo "azurerm provider is NOT locked!"
            exit 1
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan-${TF_VAR_environment}.out